CivMC/Civ

plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/DespawnFix.java
plugins/simpleadminhacks-paper/src/main/resources/config.yml

At high despawn ranges, mobs might not have the chance to despawn before they are unloaded. This fix forcibly despawns the mob when it is unloaded.

Add a fix for high despawn ranges

---

plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/database/GroupManagerDao.java

When a group is deleted, it is "merged" into the Name_layer_special group by adding a redirection from the original group's ID to Name_layer_special's ID in the faction_id table.
Then, it deletes all members of the group. However, that breaks this statement which is an INNER JOIN, and only returns a row if there is a row in both tables.
Since the deleted group does not have any members, this query will not return the deleted group's ID, and that ID will not be associated with this group.
This caused a problem, because the deleted group's ID is still associated with all the reinforcements with that group. Whenever the group of a reinforcement is looked up, it will find the Name_layer_special group through the faction_id table's association. However, the lookup will not be cached, because …

Fix lag when loading the Name_layer_special group

---

plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/gui/GUIGroupOverview.java
plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/gui/MainGroupGUI.java

- Sort all groups by their rank, and then their name
- Sort members of groups by their rank, and then their name
- Show /nlpp and /nlrm command hints (most people don't seem to be aware of these commands)

Make the /nl GUI easier to use

---

plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/InventoryListener.java
plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/listener/ExileListener.java
plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java

This uses 0.5%-1% of a tick by copying loads of data around that we never use, this uses the new getHolder(boolean) method added by https://github.com/PaperMC/Paper/pull/3535, which is much faster.

Don't use snapshots with getHolder

---

plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/CommandHelpers.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/CommandManager.java

Copied over from https://github.com/CivMC/CivModCore/pull/90
> This PR does four things:
> 
> 1. Reimplements the fix from https://github.com/CivMC/CivModCore/pull/77.
> 
> 2. The command completions `@none`, `@materials`, and `@itemMaterials` are separated into a separate helper class (see its javadoc). These completions are also made static, which should further improve performance (even if only slightly) from the optimisations from https://github.com/CivMC/CivModCore/pull/74.
> 
> 3. Added a ConsoleCommandSender context, allowing for:
> ```
> @CommandAlias("cmc")
> public class ExampleCommand extends BaseCommand {
>     @Subcommand("example")
>     public void run(ConsoleCommandSender sender) { // Only the console can execute this command
>         // some code here
>     }
> }
> ```
> …

Fix and optimise ACF extensions

---

plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/entities/EntityUtils.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/EnchantUtils.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/ItemUtils.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/MaterialUtils.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/PotionUtils.java

Copied over from https://github.com/CivMC/CivModCore/pull/103
> Save for the PotionUtils class where some custom translation-finding stuff is, these methods can be entirely fobbed off to Kyori.

Remove asTranslatable

---

plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/MapCopyProtection.java
plugins/simpleadminhacks-paper/src/main/resources/config.yml
plugins/simpleadminhacks-paper/src/main/resources/plugin.yml

Maps can be copy protected by running `/copyprotect` while holding a filled map. Copy protected maps may still be locked and have their scale changed, but may not be copied in either a cartography table or a crafting interface.
Same as https://github.com/CivMC/SimpleAdminHacks/pull/80. Moved over because of the switch to a monorepo.

Add Map Copy Protection

---

plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/BlockListener.java

Block removing and placing plants in flower pots if the player doing so does not have the appropriate permissions

Prevent Innapropriate Flower Pot Modification

---

plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/listeners/AssociationListener.java

`PlayerLoginEvent` is called before the connection is assigned, moving the `setPlayerProfile` call to the `PlayerJoinEvent` listener fixes this as by that point the connection has been assigned.

Fix null connection error in NameLayer 1.20

---

plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/commands/NameCommand.java

Changes the rename feedback to no longer give a blank name if the snitch being renamed previously had no name.

Make `/janame` feedback a bit nicer

---

plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/abstr/LoggableBlockAction.java

Copied over from https://github.com/CivMC/JukeAlert/pull/51
> Was only intending to update getGUIRepresentation() and then got a bit carried away.
> 
> - Renamed the internal fields and parameters to be more accurate.
> 
> - Updated any usage of internals to their getters instead.
> 
> - getGUIRepresentation() now has an extensive switch to convert block-only materials to their item variant. Was conflicted on whether to put this in CivModCore instead, but this is more or less only for JukeAlert's GUI, not for loot-tables or similar feature. This will also print a warning if any block->item matches are missing (good for future proofing).
> 
> - getGUIRepresentation() will also show the block's material in every GUI log, instead of just the logs that failed to display (which I don't think …

Fixup LoggableBlockAction (fixes #213)

---

plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/gui/MainGroupGUI.java

Currently when loading a group page it first checks whether this page would be empty or not, but does so assuming 5 instead of 4 rows of member slots (45 instead of 36 slots) are shown per page, therefore it can incorrectly decide to reload the prior page.

Fix show next page

---

plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/gui/MainGroupGUI.java

'Go to previous page' button is set to slot 45 when currentPage > 0, conflicting with 'Return to overview' which is afterwards set to slot 45 in all cases thus the previous page button never shows up. Id guess intended was for the latter to only be available on the first page?

Fix show previous page

---

plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/gui/FastMultiPageView.java
plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/gui/SnitchOverviewGUI.java
plugins/jukealert-paper/src/main/resources/plugin.yml

- Only render the snitches for the current page
- Use components instead of adding text lore (this is about 90% faster than the previous method)
- Also fix the plugin name (previously it was jukealert-paper, now it correctly shows as JukeAlert)

Optimise snitch GUI

---

plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/abstr/LoggablePlayerAction.java
plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/abstr/PlayerAction.java

Copied from https://github.com/CivMC/JukeAlert/pull/48
> This switches the how timestamps are rendered in snitch logs from "2011-12-03T10:15:30" to "Tue, 3 Jun 2008 11:05:30 GMT". It retains the old format for chat outputs for compaction and mod-parsing reasons.

Improve time formatting in snitch logs

---

plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/command/CmdShowAllPearls.java

Added a button to `/ep showall` menu to toggle banned pearls and turned them off by default. Toggle shares cooldown with command as it essentially reruns the command each time it's clicked but with the filter on or off.
https://github.com/CivMC/Civ/assets/14056973/4b3cd5af-6b47-428a-b658-6775cddc3fe7

Add a toggle to enable/disable banned pearls in ep showall

---

plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/AntiDerailment.java
plugins/simpleadminhacks-paper/src/main/resources/config.yml

If a minecart is going to derail because it is going too fast, this fix will backtrack its movement and move it as if it was going 8m/s. This will slow down the minecart slightly but prevent derailment.
This does not fix fast minecarts being unable going up hills or minecarts jumping across tracks.

A partial fix for minecart derailment

---

plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/HorseStats.java

The `PlayerInteractEntityEvent` event fires twice, once for both of the players hands, so the message was displayed twice. Only occurs if the stats are checked whilst another player is riding the horse, but ignoring the offhand version of the event fixes it.

Fix horse stats message double sending

---

plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/RedstoneListener.java

Fix to allow floor/ceiling buttons placed backwards to open doors

Fix to allow floor/ceiling buttons placed backwards to open doors

---

plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/CivModCorePlugin.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/CommandHelpers.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/CommandManager.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/players/PlayerNames.java

Fixes #336 more comprehensively by fulfilling the TODO in CommandManager.

Create centralised player-name cache

---

plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/GameFixes.java

This hack prevents you from right clicking respawn anchors at all, this fix makes sure that it only prevents the respawn anchor from exploding, but doesn't prevent you placing blocks.

Prevent respawn anchors being used as anti-place

---

plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/BlockListener.java

Previously players were not able to use potions on top of these kinds of blocks or place blocks on top of them with shift right click. This change will allow that behaviour.

Allow interacting with chests and trapdoors if doing so would not actually open them

---

plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/listeners/CivChat2Listener.java
plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/utility/ScoreboardHUD.java

Due to the new changes with the scoreboard where it now updated when you log in, it might try and show you as messaging a player who is offline. This change will no longer show you as messaging players who are offline and will also automatically disable messaging them.

Fix NPE in CivChat

---

plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/SparseQuadTree.java

A quick fix for the large memory usage of this object, HashSet uses an empty object as a value of each element in its set, but OpenObjectHashSet doesn't rely on HashMap, has no values, and is therefore more memory efficient.

Replace HashSet with OpenObjectHashSet

---

plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/CivModCorePlugin.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/ChunkMetaCommand.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkMetaListener.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/WorldChunkMetaManager.java
plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/table/TableBasedBlockChunkMeta.java

Hopefully this can be used to diagnose the issue

Add logging for ChunkMeta

---

ansible/templates/stacks/auth.yml
ansible/templates/stacks/monitoring.yml

With the fixes to private config, this fixes auth and Grafana.

Update auth and monitoring templates

---

plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/ItemMap.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/factories/FurnCraftChestFactory.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/DecompactingRecipe.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/IRecipe.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PlayerHeadRecipe.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintBookRecipe.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintNoteRecipe.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintingPlateJsonRecipe.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintingPlateRecipe.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/ProductionRecipe.java
plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/RandomOutputRecipe.java

Fixes FactoryMod incorrectly believing that recipe output would fit in a chest because of some incorrect uses of `ItemMap`'s `fitsIn` and an issue with `fitsIn` itself.

Fix Factory Overflow

---

plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/commands/IgnoreList.java

Refactors `/ignorelist` to use Kyori components. Each ignored player/group is underlined and clickable and will unobtrusively copy the un-ignore command to the clipboard.
Before:
After:

Refactor /ignorelist command

---

plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/PortalModifyHack.java

If you are falling really fast, you will be falling multiple blocks per second, and could possibly pass straight through an end portal. This fix changes the hack to use an event triggered earlier to detect if a player passes through an end portal.

Fix portal hack not triggering

---

plugins/finale-paper/src/main/java/com/github/maxopoly/finale/listeners/PotionListener.java

Fixes what's known as a "pot glitch" where throwing a health potion at the right time can revive a dead player.
Duplicate of https://github.com/CivMC/Civ/pull/326 because I messed up and put that one on the main branch of my fork.

Don't heal dead entities with health potions

---

ansible/files/paper-config/plugins/CivDuties/config.yml

If the published config is what's used on live then this fixes #427

Superfriend snitch fix

---

plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/PortalModifyHack.java

That was being based on PlayerPortalEvent, which is no longer being called. The fix is to manually call the event.
Tested on the test server and validated that pearled players cannot go through portals, and also that pearls are dropped if you try and take them through portals.

Fix pearled players going through portals

---

plugins/combattagplus-paper/src/main/java/net/minelink/ctplus/nms/NpcPlayer.java
plugins/combattagplus-paper/src/main/java/net/minelink/ctplus/nms/NpcPlayerHelperImpl.java

This reverts commit 5d2151f1cd458b66db140586924c28cb20cb698d, from PR https://github.com/CivMC/CombatTagPlus/pull/21.
This fixes players losing their bed position as well as players losing their crafting recipes and xp (https://github.com/CivMC/Civ/issues/93), because the fact that the UUID is the same, combined with https://github.com/CivMC/Civ/blob/f525b7afeb0fa63e4cef3e48c3ec1d7dc790fc5d/plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java#L303, causes an interaction where the player's saved data is overriden with the NPC's data, which has *most* things copied but not the bed location. This change seems pretty broken, and was only applied recently with the 1.20 update, so I decided to roll it back until we implement a fix for everything. …

Revert "Discard entities before adding NPCs"

---

plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/database/JukeAlertDAO.java

The problem with snitches crashing the server is that the MariaDB query planner decides that it is going to be smart, and actually do a query from the (very small) ja_snitch_actions table, and then join the (humongous) ja_snitch_entries table.
To do this, it has the genius idea of filtering the ja_snitch_entries table by the type_id column. This column represents the type of snitch entry, be it entering the snitch, breaking a block, placing a block, etc. Naturally, MariaDB thinks that it can reduce the 10M+ row database to just 1000 rows with this filter. But it turns out that there are LOTS of entries for each type_id, so it actually get about 600K columns, and has to linearly search through them.
Only a handful of snitches have been found to crash the server this way. I don't know how …

Fix some snitches crashing the server

---

ansible/files/paper-config/spigot.yml

This should fix arrows and such disappearing. It shouldn't really impact lag except maybe client-side in Altepetl but they had it comnig.

Bump entity render distances to default settings

---

ansible/files/paper-config/plugins/CastleGates/config.yml

This fixes the issue noted [here](https://discord.com/channels/912074050086502470/952314940176363570/1259737460020350986). 
32 is a relatively arbitrary number that should allow castlegates of reasonable size to function when laid out in the fashion seen in the linked screenshots, if there's a reason it was set so low/could go higher I'm open to suggestions.

Increase MaxPowerTransfers

---

plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/EntityListener.java

Stops players breaking their own reinforcement when stripping blocks on their group
It also stops being able to break logs/copper by stripping instead of breaking the block

Prevent stripping logs & copper from damaging reinforcement

---

plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/ExilePearl.java
plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/command/CmdAdminSetHealth.java
plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/core/CoreExilePearl.java
plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/core/CoreLoreGenerator.java
plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java

This PR Does not include any changes to pearl cost.
It only changes the way we display pearl health, showing the actual health value instead of a percentage.
Additionally, it updates the "Cost per day" to reflect how much of this health the pearl is actually using.
Fresh pearl:
Refueling preview:
Refueling output:
Four year old pearl:

Show pearl health value instead of percent

---

plugins/essenceglue-paper/src/main/java/com/github/maxopoly/essenceglue/reward/VirtualRewarder.java

Before:
>  Use /essence withdraw to claim your essence.
After:
> Use /essence withdraw to materialise all of your essence as an item.
"Claim" implies that if i do not run the proposed command I will not receive the daily essence and that the command will only apply to the essence that I've just received, not to all the essence in my pouch.
I simply used the already existing wording from https://github.com/CivMC/Civ/blob/main/plugins/essenceglue-paper/src/main/java/com/github/maxopoly/essenceglue/commands/EssenceCommand.java#L36

Fix  ambiguous essence claim message

---

ansible/files/paper-config/plugins/MobLimit/config.yml

Sets a natural spawning limit on turtles. if there's more than 8 in a 32 block radius.

Too many turtles

---

ansible/files/paper-config/plugins/FactoryMod/config.yml

Adds repair kits for: 
* gem factory
* grill
* ore smelter
* adv ore smelter
* elite ore smelter
* rail
* husbandry
* forge
* redstone
* bastion
* basic cauldron
* advanced cauldron
* printer
* research
* concrete
* bio
* copper
- Adds a recipe in rail factory to make Activator rails.
costing 18 iron and 2 redstone to produce 32 activator rails. Same as the detector recipe.
- Adds recipes for mangrove/cherry wood to charcoal in the charcoal factory
- Adds recipes to dye froglights to the verdant and ochre versions in the aesthetics factory. 
I simplified the copper workshop repair recipe, needing 16 of every oxidation level seemed just an annoyance. Made it 64 normal copper blocks instead.
Also removes the Elytra recipe because it wasn't being used in a factory anyways. 
Resolves #711, …

Factorymod additions. 

---

plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/ChatStrings.java
plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/CivChat2Manager.java
plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/commands/Afk.java
plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/commands/GlobalChat.java

Make a simple patch that lets players set a custom afk message. Still need to decide if the custom message should be added onto the default message or not.
Demo:
`/afk This is a highly custom message from a very dumb person, please forgive me my good sir`

add ability to set custom afk message

---

plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/core/CoreLoreGenerator.java

This updates the pearl-lore generator to use the same date formatter as `/ep showall`.
Here's what the date looks like on the pearl:
Which is confusing to non-Americans, compared to what is shown on `/ep showall`:

Date parity between pearls and /ep showall

---

ansible/files/paper-config/plugins/MobLimit/config.yml

They have no use and are annoying. No reason for there to be so many.

Fuck dolphins
